# Homework 2 - Part 1 (Woosoo Kim)

1. Import Numpy

In [1]:
import numpy as np

2. Create two Numpy arrays:
 -  `array1` = ranges from 0 to 9
 - `array2` = ranges from 0 to 27 by 3

Each array should have exactly 10 elements.

In [2]:
array1 = np.array(list(range(0, 10)))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array2 = np.array(list(range(0, 28, 3)))
array2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

3. Create `M1`, a matrix made up of `array1` and `array2`

In [4]:
M1 = np.array([array1, array2])
M1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

4. Create a new array, `M2`, that slices `M1` into to include all rows and only the last 3 columns 

In [5]:
M2 = M1[:, -3:]
M2

array([[ 7,  8,  9],
       [21, 24, 27]])

5. Create a new array, `M3`, of uniformly distributed random numbers that is 3 by 3 in dimension.

In [6]:
M3 = np.random.random([3, 3])
M3

array([[0.68573024, 0.65660231, 0.96406721],
       [0.23027002, 0.78462963, 0.94816409],
       [0.33043274, 0.50321336, 0.58198937]])

6. Re-create `M3` but with seed=1 and multiply each element by 1000

In [7]:
np.random.seed(1)
M3 = np.random.random([3, 3]) * 1000
M3

array([[4.17022005e+02, 7.20324493e+02, 1.14374817e-01],
       [3.02332573e+02, 1.46755891e+02, 9.23385948e+01],
       [1.86260211e+02, 3.45560727e+02, 3.96767474e+02]])

7. Create an array, `array3`, of normally distributed numbers, with dimensions 10 rows by 4 columns. Set seed=3.  

In [8]:
np.random.seed(3)
array3 = np.random.randn(10, 4)
array3

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898, -0.08274148, -0.62700068],
       [-0.04381817, -0.47721803, -1.31386475,  0.88462238],
       [ 0.88131804,  1.70957306,  0.05003364, -0.40467741],
       [-0.54535995, -1.54647732,  0.98236743, -1.10106763],
       [-1.18504653, -0.2056499 ,  1.48614836,  0.23671627],
       [-1.02378514, -0.7129932 ,  0.62524497, -0.16051336],
       [-0.76883635, -0.23003072,  0.74505627,  1.97611078],
       [-1.24412333, -0.62641691, -0.80376609, -2.41908317],
       [-0.92379202, -1.02387576,  1.12397796, -0.13191423]])

8. Find the mean and st. dev. of `array3`

In [9]:
array3.mean()

np.float64(-0.17687217694521734)

In [10]:
array3.std()

np.float64(1.0012852082549313)

9. Take the log+1 of `array3`.  Call it `array4`.

In [11]:
array4 = np.log(array3) + 1
array4

/var/folders/nf/pr_zbg4n09l0wk9d51jnb0xc0000gn/T/ipykernel_7233/2193220283.py:1: RuntimeWarning: invalid value encountered in log
  array4 = np.log(array3) + 1


array([[ 1.58144911,  0.17105566, -1.33823851,         nan],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,  0.87740559],
       [ 0.87366328,  1.53624367, -1.99505966,         nan],
       [        nan,         nan,  0.98221013,         nan],
       [        nan,         nan,  1.39618778, -0.44089304],
       [        nan,         nan,  0.53038824,         nan],
       [        nan,         nan,  0.70570446,  1.68113066],
       [        nan,         nan,         nan,         nan],
       [        nan,         nan,  1.11687414,         nan]])