## What is Numpy

Numpy is one of the fundamental Python packages for data science because of its ability to manipulate numerical data.  Many other packages in the PyData ecosystem are built upon Numpy.

Numpy works primarily with arrays and matrices.  An array is a one-dimensional vector, while a matrix is a two-dimensional array.  

Numpy is shorthand for "numerical Python".  

*You need to install Numpy before moving on.  It should be included with your Anaconda installation, but if not, please pip install the Numpy library.*


In [1]:
#It is the convention to use np as the shortcut for numpy.
import numpy as np

In [2]:
#create an array
a0 =list(range(1,6))
a1 = np.array(a0)
a1

array([1, 2, 3, 4, 5])

In [3]:
#create a second array, b1
b0 =list(range(10,20, 2))
b1 = np.array(b0)
b1


array([10, 12, 14, 16, 18])

In [4]:
#create a matrix, A
A = np.array([a1,b1])
A

array([[ 1,  2,  3,  4,  5],
       [10, 12, 14, 16, 18]])

In [5]:
A.ndim

2

In [6]:
b1.ndim

1

In [7]:
A.shape

(2, 5)

In [8]:
A.size

10

### Slicing arrays and matrices

In [9]:
c1 = np.arange(10,21)
c1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
c1[5]

15

In [11]:
c1[5:]

array([15, 16, 17, 18, 19, 20])

In [12]:
c1[:5]

array([10, 11, 12, 13, 14])

In [13]:
c1[2:8]

array([12, 13, 14, 15, 16, 17])

In [14]:
A

array([[ 1,  2,  3,  4,  5],
       [10, 12, 14, 16, 18]])

In [15]:
A[1,4]

18

In [16]:
new_array = A[:,3:]

In [17]:
new_array

array([[ 4,  5],
       [16, 18]])

### Random numbers

In [18]:
# create a 1d array of uniformly distributed numbers (floats) over [0, 1).
np.random.random(10)


array([0.87610658, 0.26513489, 0.01314372, 0.29460438, 0.90888961,
       0.70685803, 0.17394502, 0.64534699, 0.42468722, 0.34111376])

In [19]:
np.random.random([10,10])

array([[0.13095868, 0.22173038, 0.05206104, 0.90982212, 0.45352623,
        0.34438792, 0.99769013, 0.76959929, 0.19602832, 0.4906743 ],
       [0.37977098, 0.94551651, 0.40943195, 0.78331029, 0.54338849,
        0.48925742, 0.27589137, 0.71475532, 0.34757595, 0.39690204],
       [0.10394299, 0.86235605, 0.04330286, 0.53579985, 0.59577684,
        0.33570342, 0.97493672, 0.3380781 , 0.28420868, 0.5914584 ],
       [0.62237503, 0.521927  , 0.03745312, 0.99548963, 0.64108574,
        0.49867812, 0.24760019, 0.5915029 , 0.95621727, 0.25168427],
       [0.20958039, 0.32474302, 0.8404562 , 0.93144109, 0.72232075,
        0.65224626, 0.44590044, 0.23596891, 0.08793594, 0.20308129],
       [0.9704056 , 0.95850041, 0.34935592, 0.44739372, 0.58804254,
        0.50978464, 0.81192478, 0.84034848, 0.79219384, 0.50311532],
       [0.07043942, 0.5108316 , 0.3593809 , 0.26432007, 0.25679482,
        0.77294669, 0.15916   , 0.17316831, 0.33139965, 0.68711298],
       [0.2648758 , 0.53016254, 0.2650773

In [20]:
np.random.seed(0)
np.random.random(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [21]:
# create a 1d array of normally-distributed numbers centered at 0.
np.random.seed(0)
np.random.randn(50)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574,
       -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
       -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877,
        0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
        0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275,
       -1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
       -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028])

In [22]:
np.random.seed(0)
np.random.randn(5,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462]])

In [23]:
# report a single number from an interval [start, end, #].
#np.random.seed(63)
np.random.randint(1,1000000)

714661

In [24]:
np.random.choice([1,2,3,4,5], 10, replace=True)

array([1, 5, 2, 5, 2, 3, 3, 1, 2, 2])

### Numeric functions using Numpy

In [25]:
# create a 1d array of normally-distributed numbers (floats) centered at 0.
np.random.seed(100)
d1 = np.random.randn(50)
d1

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144,
       -0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081,
       -0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825,
        1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869,
        0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601,
        0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476,
       -0.45594693,  1.18962227, -1.69061683, -1.35639905, -1.23243451,
       -0.54443916, -0.66817174,  0.00731456, -0.61293874,  1.29974807,
       -1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387])

In [26]:
d1.max()

1.6189816606752596

In [27]:
d1.min()

-1.7497654730546974

In [28]:
d1.mean()

-0.040800707873950195

In [29]:
d1.std()

0.941220049285939

In [30]:
np.max(d1)

1.6189816606752596

In [31]:
np.median(d1)

-0.04854829008086233

In [32]:
# 최대값의 위치를 반환
np.argmax(d1)

20

In [33]:
# 최값의 위치를 반환
np.argmin(d1)

0

### Element-wise functions using Numpy

In [34]:
d1

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144,
       -0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081,
       -0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825,
        1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869,
        0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601,
        0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476,
       -0.45594693,  1.18962227, -1.69061683, -1.35639905, -1.23243451,
       -0.54443916, -0.66817174,  0.00731456, -0.61293874,  1.29974807,
       -1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387])

In [35]:
d2 = np.abs(d1)
d2

array([1.74976547, 0.3426804 , 1.1530358 , 0.25243604, 0.98132079,
       0.51421884, 0.22117967, 1.07004333, 0.18949583, 0.25500144,
       0.45802699, 0.43516349, 0.58359505, 0.81684707, 0.67272081,
       0.10441114, 0.53128038, 1.02973269, 0.43813562, 1.11831825,
       1.61898166, 1.54160517, 0.25187914, 0.84243574, 0.18451869,
       0.9370822 , 0.73100034, 1.36155613, 0.32623806, 0.05567601,
       0.22239961, 1.443217  , 0.75635231, 0.81645401, 0.75044476,
       0.45594693, 1.18962227, 1.69061683, 1.35639905, 1.23243451,
       0.54443916, 0.66817174, 0.00731456, 0.61293874, 1.29974807,
       1.73309562, 0.9833101 , 0.35750775, 1.6135785 , 1.47071387])

In [36]:
d2 = np.exp(d1)
d2

array([0.1738147 , 1.40871847, 3.16779513, 0.7769059 , 2.66797775,
       1.67233164, 1.24754756, 0.34299365, 0.82737617, 1.29046348,
       0.63253041, 1.54521566, 0.55788912, 2.26335239, 1.95956166,
       0.90085484, 0.58785182, 2.80031717, 0.64523827, 0.32682898,
       5.04794718, 4.67208376, 0.77733868, 0.43066027, 1.20263946,
       2.55252279, 2.07715744, 3.90226099, 0.72163338, 1.05725509,
       1.24907042, 0.23616679, 0.46937545, 2.26246293, 2.11794179,
       0.63384748, 3.28583981, 0.18440574, 0.25758667, 0.29158185,
       0.58016707, 0.51264497, 1.00734138, 0.54175645, 3.6683724 ,
       0.17673645, 0.37407084, 1.42976165, 0.19917359, 4.35234102])

In [37]:
d2 = np.log(d1)
d2

/var/folders/dt/31_473f9129gq8009hs6znhh0000gn/T/ipykernel_31464/3296390883.py:1: RuntimeWarning: invalid value encountered in log
  d2 = np.log(d1)


array([        nan, -1.07095703,  0.14239829,         nan, -0.01885587,
       -0.66510634, -1.50877992,         nan,         nan, -1.36648607,
               nan, -0.83203348,         nan, -0.20230338, -0.39642489,
               nan,         nan,  0.02929924,         nan,         nan,
        0.48179735,  0.43282419,         nan,         nan, -1.69000452,
       -0.06498427, -0.31334135,  0.30862826,         nan, -2.88820584,
       -1.50327948,         nan,         nan, -0.20278469, -0.28708923,
               nan,  0.17363583,         nan,         nan,         nan,
               nan,         nan, -4.91788796,         nan,  0.26217046,
               nan,         nan, -1.02859823,         nan,  0.38574791])

In [38]:
d3 = d2 + d2
d3

array([        nan, -2.14191407,  0.28479658,         nan, -0.03771175,
       -1.33021269, -3.01755985,         nan,         nan, -2.73297214,
               nan, -1.66406697,         nan, -0.40460677, -0.79284977,
               nan,         nan,  0.05859848,         nan,         nan,
        0.96359469,  0.86564839,         nan,         nan, -3.38000903,
       -0.12996855, -0.6266827 ,  0.61725651,         nan, -5.77641168,
       -3.00655895,         nan,         nan, -0.40556939, -0.57417847,
               nan,  0.34727167,         nan,         nan,         nan,
               nan,         nan, -9.83577591,         nan,  0.52434091,
               nan,         nan, -2.05719646,         nan,  0.77149581])

In [39]:
d2**2

array([           nan, 1.14694897e+00, 2.02772737e-02,            nan,
       3.55543944e-04, 4.42366447e-01, 2.27641686e+00,            nan,
                  nan, 1.86728418e+00,            nan, 6.92279718e-01,
                  nan, 4.09266593e-02, 1.57152690e-01,            nan,
                  nan, 8.58445439e-04,            nan,            nan,
       2.32128684e-01, 1.87336784e-01,            nan,            nan,
       2.85611527e+00, 4.22295569e-03, 9.81828009e-02, 9.52514000e-02,
                  nan, 8.34173296e+00, 2.25984919e+00,            nan,
                  nan, 4.11216316e-02, 8.24202276e-02,            nan,
       3.01494032e-02,            nan,            nan,            nan,
                  nan,            nan, 2.41856219e+01,            nan,
       6.87333485e-02,            nan,            nan, 1.05801432e+00,
                  nan, 1.48801447e-01])