# 2. The Basics of NumPy Arrays

## 2-1. NumPy Array Attributes

In [13]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [14]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [15]:
print("dtype: ", x3.dtype)

dtype:  int64


## 2-2. Array Indexing: Accessing Single Elements

In [16]:
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x1[0]

5

In [18]:
x1[0]

5

In [19]:
x1[4]

7

In [20]:
x1[-1]

9

In [21]:
x1[-2]

7

In [22]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x2[0, 0]

3

In [24]:
x2[2, -1]

7

In [25]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [26]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

## 2-2. Array Slicing: Accessing Subarrays

### 2-2-1. One-dimensinal subarrays

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[5:]

array([5, 6, 7, 8, 9])

In [30]:
x[4:7]

array([4, 5, 6])

In [31]:
x[::2]

array([0, 2, 4, 6, 8])

In [32]:
x[1::2]

array([1, 3, 5, 7, 9])

In [33]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
x[5::-2]

array([5, 3, 1])

### 2-2-2. Multi-dimensional subarrays

In [35]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [36]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [37]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [38]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### 2-2-3. Accessing array rows and columns

In [39]:
print(x2[:, 0])

[12  7  1]


In [40]:
print(x2[0, :])

[12  5  2  4]


In [41]:
print(x2[0])

[12  5  2  4]


## 2-3. Subarrays as no-copy views

In [42]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [43]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [44]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [45]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 2-4. Creating copies of arrays

In [46]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [47]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [48]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 2-5. Reshaping of Arrays

In [49]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
x = np.array([1, 2, 3])
x.reshape(1, 3)

array([[1, 2, 3]])

In [51]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [52]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [53]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 2-6. Array Concatenation and Splitting

### 2-6-1. Condatenation of arrays

In [54]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [55]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [56]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### 2-6-2. Splitting of arrays

In [61]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [62]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
